vich_uploader:
    db_driver: orm

    mappings:
      user_image:
        inject_on_load: true
        uri_prefix: /upload/images/users
        upload_destination: '%kernel.project_dir%/public/upload/images/users'
        namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

